### ISSUE TITLE
Run CMD "mvn graphwalker:test" unsuccessfully with the default appium demo

### ISSUE THREAD

**Issue by afdsghjk** [GraphWalker/graphwalker-example#12] opened 2016-09-28 03:29 UTC
I followed the appium demo, but got the following error after running the CMD "mvn graphwalker:test", please help me to find out the problem:
[ERROR] No plugin found for prefix 'graphwalker' in the current project and in t
he plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from th
e repositories [local (C:\Users\Tong\.m2\repository), central (https://repo.mave
n.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundF
orPrefixException

**Comment by KristianKarl** [comment] 2016-09-28 05:51
Fixed by 2fa75f6eb20115e050cb3f8686b50551ffffa61d

**Comment by KristianKarl** [comment] 2016-09-28 05:51
Thanks for the report

**Closed by KristianKarl** 2016-09-28 05:51 UTC

**Comment by nilols** [comment] 2016-09-28 06:13
I think the actual error, even if versioning was wrong, maven report here is due to a missing definition in your settings file, a few years back a change was made for plugin resolutions in maven and now, if I'm correct you'll have to define a <pluginGroup/> for org.graphwalker if you want to run mvn graphwalker:<goal>, see https://maven.apache.org/settings.html#Plugin_Groups

If someone encounters the same issue and don't wanna change the settings.xml you could also use the plugin groupId directly on the command line, something like, mvn org.graphwalker:graphwalker-maven-plugin:test

**Comment by KristianKarl** [comment] 2016-09-28 07:56
I gonna cleanup the examples, so that they passes ci tests. I think this will remedy the root cause of this issue as well: https://github.com/GraphWalker/graphwalker-example/issues/11

**Comment by afdsghjk** [comment] 2016-10-08 03:33
Thank you for help. I have tried again following the example, now the error is "[ERROR] No suitable context factory found
[ERROR] No suitable context factory found". May I ask are there any mistakes I have made?
